function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
    "A romantic candlelit dinner would be incomplete without __________.",
    "After storm eunice, Boris Johnson brought __________ to the people of London.",
    "After the earthquake, Will Smith brought __________ to the people of New York.",
    "Alternative medicine is now embracing the curative powers of __________.",
    "And I would have gotten away with it, too, if it hadn't been for __________.",
    "Explorers have recently discovered a primitive tribe that worships __________.",
    "I can't have just one! I love __________!",
    "But before I kill you, Mr. Bond, I must show you __________.",
    "Coming to Broadway this season, __________: The Musical.",
    "Dear Abby, I'm having some trouble with __________ and would like your advice.",
    "Due to a PR fiasco, Tesco no longer offers __________.",
    "During Picasso's often-overlooked Dark Period, he produced hundreds of paintings of __________.",
    "During sex, I like to think about __________.",
    "He who controls __________ controls the world.",
    "How am I maintaining my relationship status? __________",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "I drink to forget __________.",
    "I learned the hard way that you can't cheer up a grieving friend with __________.",
    "I wish I hadn't lost the instruction manual for __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "In London County Jail, word is you can trade 200 cigarettes for __________.",
    "In Michael Jackson's final moments, he thought about __________.",
    "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
    "In his new self-produced album, Kanye West raps over the sounds of __________.",
    "In its new tourism campaign, Birmingham proudly proclaims that it has finally eliminated __________.",
    "In the distant future, historians will agree that __________ marked the beginning of America's decline.",
    "In the distant future, historians will agree that __________ marked the beginning of England's decline.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time. ",
    "Instead of coal, Santa now gives the bad children __________.",
    "It's a pity that kids these days are all getting involved with __________.",
    "Life for Native Americans was forever changed when the White Man introduced them to __________.",
    "Life was difficult for cavemen before __________.",
    "MTV's new reality show features eight washed-up celebrities living with __________.",
    "Major League Baseball has banned __________ for giving players an unfair advantage.",
    "Maybe she's born with it. Maybe it's __________.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "Next on Sky Sports: The World Series of __________.",
    "Science will never explain the origin of __________.",
    "Sorry everyone, I just __________.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
    "TSA guidelines now prohibit __________ on airplanes.",
    "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.",
    "The class field trip was completely ruined by __________.",
    "The communist governments of Scandinavia have declared that access to __________ is a basic human right.",
    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __________.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
    "When I'm in prison, I'll have __________ smuggled in.",
    "When all else fails, I can always masturbate to __________.",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
    "Why am I sticky?",
    "Why can't I sleep at night?",
    "Why do I hurt all over?",
    "__________: Good to the last drop.",
    "__________: Kid-tested, mother-approved.",
    "__________: good to the last drop.",
    "__________? There's an app for that.",
    "What is an appropriate name for a water park? __________",
    "AJ on a date would be incomplete without __________"
  ];
}

function white() {
  return [
   "72 virgins",
   "#RishiAbuseIsNotOkay",
   "8 oz. of sweet Mexican black-tar heroin",
   "A Super Soaker™ full of cat pee",
   "A big black dick",
   "A bleached asshole",
   "A bloody pacifier",
   "A brain tumor",
   "A cooler full of organs",
   "A crappy little hand",
   "A death ray",
   "A defective condom",
   "A disappointing birthday party",
   "A drive-by shooting",
   "A fetus",
   "A gentle caress of the inner thigh",
   "A good sniff",
   "A hot mess",
   "A lifetime of sadness",
   "A low standard of living",
   "A micropenis",
   "A middle-aged man on roller skates",
   "A mime having a stroke",
   "A moment of silence",
   "A monkey smoking a cigar",
   "A depressed zoo lion",
   "A nuanced critique",
   "A really cool hat",
   "A sad handjob",
   "A snapping turtle biting the tip of your penis",
   "A stray pube",
   "A thermonuclear detonation",
   "A time travel paradox",
   "A tiny horse",
   "A web of lies",
   "A windmill full of corpses",
   "A zesty breakfast burrito",
   "AIDS",
   "AXE Body Spray",
   "Aaron Burr",
   "Active listening",
   "Actually taking candy from a baby",
   "Adderall™",
   "Agriculture",
   "Alcoholism",
   "All-you-can-eat shrimp for $4.99",
   "Altar boys",
   "Amputees",
   "Boris Johnson",
   "The UK Government",
   "An asymmetric boob job",
   "An erection that lasts longer than four hours",
   "Anal beads",
   "Another goddamn vampire movie",
   "Apologizing",
   "Arnold Schwarzenegger",
   "Autocannibalism",
   "BATMAN!!",
   "Balls",
   "Barack Obama",
   "Beating your wives",
   "Bees",
   "Being a busy adult with many important things to do",
   "Being a dick to children",
   "Being a dinosaur",
   "Being a motherfucking sorcerer",
   "Being fabulous",
   "Being marginalized",
   "Being on fire",
   "Being rich",
   "Bill Nye the Science Guy",
   "Bingeing and purging",
   "Bitches",
   "Bling",
   "Booby-trapping the house to foil burglars",
   "Boogers",
   "Bosnian chicken farmers",
   "Breaking out into song and dance",
   "Britney Spears at 55",
   "Cards Against Humanity",
   "Olly Newport",
   "Rishi",
   "Catapults",
   "Chainsaws for hands",
   "Charisma",
   "Cheating in the Special Olympics",
   "Child abuse",
   "Child beauty pageants",
   "Children on leashes",
   "Civilian casualties",
   "Coat hanger abortions",
   "College",
   "Concealing a boner",
   "Crippling debt",
   "Crystal meth",
   "Cuddling",
   "Customer service representatives",
   "Cybernetic enhancements",
   "Daddy issues",
   "Dancing with a broom",
   "Darth Vader",
   "Dead babies",
   "Dead parents",
   "Doing the right thing",
   "An NFT",
   "NFT's",
   "A cryptocurrency named 'YourMum Coin'",
   "Drinking alone",
   "Dying",
   "Elderly men",
   "Embryos",
   "Emotions",
   "Erectile dysfunction",
   "Exactly what you expect",
   "Expecting a burp and vomiting on the floor",
   "Explosions",
   "Fabricating statistics",
   "Famine",
   "Fear itself",
   "Fiery poops",
   "Fingering",
   "Flash flooding",
   "Flesh-eating bacteria",
   "Flightless birds",
   "Flying sex snakes",
   "Foreskin",
   "Forgetting the Alamo",
   "Former Prime Minister David Cameron",
   "Former President Barack Obama",
   "Free samples",
   "Friction",
   "Friendly fire",
   "Friends who eat all the snacks",
   "Friends with benefits",
   "Full frontal nudity",
   "Elon Musk",
   "Jeff Bezos",
   "Bill Gates",
   "Geese",
   "Genetically engineered super-soldiers",
   "Genital piercings",
   "Getting abducted by Peter Pan",
   "Getting drunk on mouthwash",
   "Getting naked and watching Nickelodeon",
   "Getting really high",
   "Ghosts",
   "Giving 110 percent",
   "Global warming",
   "God",
   "Good grammar",
   "Grandma",
   "Grave robbing",
   "Harry Potter erotica",
   "Heartwarming orphans",
   "Her Royal Highness, Queen Elizabeth II",
   "Hipsters",
   "Homeless people",
   "Hope",
   "Hulk Hogan",
   "Storm Eunice",
   "Incest",
   "Jerking off into a pool of children's tears",
   "Just the tip",
   "Justin Bieber",
   "Kanye West",
   "Keanu Reeves",
   "Kids with ass cancer",
   "Kim Jong-Un",
   "Land mines",
   "Leveling up",
   "Licking things to claim them as your own",
   "Literally eating shit",
   "Masturbation",
   "Mathletes",
   "Men",
   "Michael Jackson",
   "Mouth herpes",
   "Multiple stab wounds",
   "My genitals",
   "My machete",
   "My relationship status",
   "My sex life",
   "My soul",
   "My vagina",
   "Natural selection",
   "Necrophilia",
   "Not giving a shit about the Third World",
   "Obesity",
   "Old-people smell",
   "Ominous background music",
   "Oompa-Loompas",
   "Overcompensation",
   "Overpowering your father",
   "Oversized lollipops",
   "Pac-Man uncontrollably guzzling cum",
   "Panda sex",
   "Passing a kidney stone",
   "Passive-aggressive Post-it notes",
   "Pedophiles",
   "Peeing a little bit",
   "Penis envy",
   "Picking up girls at the abortion clinic",
   "Pistol-whipping a hostage",
   "Poor life choices",
   "Poor people",
   "Poorly-timed Holocaust jokes",
   "Porn stars",
   "Powerful thighs",
   "Preteens",
   "Pretending to care",
   "Pterodactyl eggs",
   "Puberty",
   "Public ridicule",
   "Pulling out",
   "Puppies",
   "Republicans",
   "Revenge fucking",
   "Riding off into the sunset",
   "Ripping into a man's chest and pulling out his still-beating heart",
   "Robert Downey Jr.",
   "Ryan Reynolds",
   "Santa Claus",
   "Science",
   "Scientology",
   "Scrotum tickling",
   "Rishi's secret sex dungeon",
   "Seduction",
   "Slow motion",
   "Smallpox blankets",
   "cum",
   "Sniffing glue",
   "shitting oneself",
   "Soup that is too hot",
   "The Queens Corgi's",
   "Sperm whales",
   "Spontaneous human combustion",
   "Stephen Hawking talking dirty",
   "Stranger danger",
   "Sudden Poop Explosion Disease",
   "Sunshine and rainbows",
   "Surprise sex",
   "Sweet, sweet vengeance",
   "Taking off your shirt",
   "Teaching a robot to love",
   "Team-building exercises",
   "Teenage pregnancy",
   "Tentacle porn",
   "The American Dream",
   "The Big Bang",
   "The Chinese gymnastics team",
   "The Donald Trump Seal of Approval™",
   "The Force",
   "The Holy Bible",
   "The Make-A-Wish Foundation",
   "The Pope",
   "The North of England",
   "Wales",
   "Russia",
   "Vladmir Putin",
   "The Russian Army",
   "Ukraine",
   "A Russian Spy",
   "The economy",
   "The heart of a child",
   "The inevitable heat death of the universe",
   "The miracle of childbirth",
   "The terrorists",
   "The true meaning of Christmas",
   "The violation of our most basic human rights",
   "Tom Cruise",
   "Too much hair gel",
   "Tweeting",
   "Two midgets shitting into a bucket",
   "Unfathomable stupidity",
   "Uppercuts",
   "Vehicular manslaughter",
   "Vikings",
   "Waiting ‘til marriage",
   "Waking up half-naked in a McDonald's parking lot",
   "Wearing underwear inside-out to avoid doing laundry",
   "When you fart and a little bit comes out",
   "Whipping it out",
   "Winking at old people",
   "Women in yogurt commercials",
   "World peace"
  ];
}

exports.getDeck = getDeck;
